In [48]:
import numpy as np

In [49]:
import pandas as pd

In [50]:
a = pd.read_csv('/content/emails.csv')
a

,text,spam
0,Subject: naturally irresistible your corporate...,1
1,Subject: the stock trading gunslinger fanny i...,1
2,Subject: unbelievable new homes made easy im ...,1
3,Subject: 4 color printing special request add...,1
4,"Subject: do not have money , get software cds ...",1
...,...,...
5723,Subject: re : research and development charges...,0
5724,"Subject: re : receipts from visit jim , than...",0
5725,Subject: re : enron case study update wow ! a...,0
5726,"Subject: re : interest david , please , call...",0


In [51]:
print(a.shape)

(5728, 2)


In [52]:
print(a.size)

11456


In [53]:
print(a.head())

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1


In [54]:
print(a.isna().sum())

text    0
spam    0
dtype: int64


In [55]:
import nltk
from nltk.stem import WordNetLemmatizer

In [56]:
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [57]:
tweets = a.text
tweets

,text
0,Subject: naturally irresistible your corporate...
1,Subject: the stock trading gunslinger fanny i...
2,Subject: unbelievable new homes made easy im ...
3,Subject: 4 color printing special request add...
4,"Subject: do not have money , get software cds ..."
...,...
5723,Subject: re : research and development charges...
5724,"Subject: re : receipts from visit jim , than..."
5725,Subject: re : enron case study update wow ! a...
5726,"Subject: re : interest david , please , call..."


In [58]:
from nltk.tokenize import TweetTokenizer
tk = TweetTokenizer()
tweets = tweets.apply(lambda x: tk.tokenize(x)).apply(lambda x: " ".join(x))
tweets

,text
0,Subject : naturally irresistible your corporat...
1,Subject : the stock trading gunslinger fanny i...
2,Subject : unbelievable new homes made easy im ...
3,Subject : 4 color printing special request add...
4,"Subject : do not have money , get software cds..."
...,...
5723,Subject : re : research and development charge...
5724,"Subject : re : receipts from visit jim , thank..."
5725,Subject : re : enron case study update wow ! a...
5726,"Subject : re : interest david , please , call ..."


In [59]:
tweets = tweets.str.replace('[^a-zA-z0-9]+',' ',regex=True)
tweets

,text
0,Subject naturally irresistible your corporate ...
1,Subject the stock trading gunslinger fanny is ...
2,Subject unbelievable new homes made easy im wa...
3,Subject 4 color printing special request addit...
4,Subject do not have money get software cds fro...
...,...
5723,Subject re research and development charges to...
5724,Subject re receipts from visit jim thanks agai...
5725,Subject re enron case study update wow all on ...
5726,Subject re interest david please call shirley ...


In [60]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [61]:
from nltk.tokenize import word_tokenize
tweets = tweets.apply(lambda x: ' '.join([i for i in word_tokenize(x) if len(i)>=3]))
tweets

,text
0,Subject naturally irresistible your corporate ...
1,Subject the stock trading gunslinger fanny mer...
2,Subject unbelievable new homes made easy wanti...
3,Subject color printing special request additio...
4,Subject not have money get software cds from h...
...,...
5723,Subject research and development charges gpg h...
5724,Subject receipts from visit jim thanks again f...
5725,Subject enron case study update wow all the sa...
5726,Subject interest david please call shirley cre...


In [62]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')
tweets = tweets.apply(lambda x: [stemmer.stem(i.lower()) for i in word_tokenize(x)]).apply(lambda x: ' '.join(x))
tweets

,text
0,subject natur irresist your corpor ident reall...
1,subject the stock trade gunsling fanni merril ...
2,subject unbeliev new home made easi want show ...
3,subject color print special request addit info...
4,subject not have money get softwar cds from he...
...,...
5723,subject research and develop charg gpg here fo...
5724,subject receipt from visit jim thank again for...
5725,subject enron case studi updat wow all the sam...
5726,subject interest david pleas call shirley cren...


In [63]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
tweets = tweets.apply(lambda x: [i for i in tk.tokenize(x) if i not in stop]).apply(lambda x: ' '.join(x))
tweets

,text
0,subject natur irresist corpor ident realli har...
1,subject stock trade gunsling fanni merril muzo...
2,subject unbeliev new home made easi want show ...
3,subject color print special request addit info...
4,subject money get softwar cds softwar compat g...
...,...
5723,subject research develop charg gpg forward shi...
5724,subject receipt visit jim thank invit visit ls...
5725,subject enron case studi updat wow day super t...
5726,subject interest david pleas call shirley cren...


In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
train_data = vec.fit_transform(tweets)
train_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 483632 stored elements and shape (5728, 28683)>

In [65]:
train_data.shape

(5728, 28683)

In [66]:
y = a['spam'].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [67]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
train_data = sc.fit_transform(train_data)
train_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 483632 stored elements and shape (5728, 28683)>

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(train_data,y,test_size=0.30,random_state=42)
x_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 342374 stored elements and shape (4009, 28683)>

In [69]:
x_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 141258 stored elements and shape (1719, 28683)>

In [70]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [71]:
y_test

array([0, 0, 0, ..., 1, 1, 0])

In [72]:
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
svm_model = SVC()
nb_model = MultinomialNB()
rf_model = RandomForestClassifier()
dt_model = DecisionTreeClassifier()
lstmodel = [svm_model,nb_model,rf_model,dt_model]

In [73]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
for i in lstmodel:
  print(i)
  i.fit(x_train,y_train)
  y_pred = i.predict(x_test)
  print('********************************************')
  print(confusion_matrix(y_test,y_pred))
  print('********************************************')
  print(classification_report(y_test,y_pred))
  print('********************************************')
  print(accuracy_score(y_test,y_pred))
  print('********************************************')

SVC()
********************************************
[[1278    0]
 [ 275  166]]
********************************************
              precision    recall  f1-score   support

           0       0.82      1.00      0.90      1278
           1       1.00      0.38      0.55       441

    accuracy                           0.84      1719
   macro avg       0.91      0.69      0.72      1719
weighted avg       0.87      0.84      0.81      1719

********************************************
0.840023269342641
********************************************
MultinomialNB()
********************************************
[[1245   33]
 [  20  421]]
********************************************
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1278
           1       0.93      0.95      0.94       441

    accuracy                           0.97      1719
   macro avg       0.96      0.96      0.96      1719
weighted avg       0.97      0.97    